export const types = {
    CARDS_POST_REQUEST: 'CARDS_POST_REQUEST',
    CARDS_POST_SUCCESS: 'CARDS_POST_SUCCESS',
    CARDS_POST_ERROR: 'CARDS_POST_ERROR',

    CARDS_GET_REQUEST: 'CARDS_GET_REQUEST',
    CARDS_GET_SUCCESS: 'CARDS_GET_SUCCESS',
    CARDS_GET_ERROR: 'CARDS_GET_ERROR',

    CARDS_PATCH_REQUEST: 'CARDS_PATCH_REQUEST',
    CARDS_PATCH_SUCCESS: 'CARDS_PATCH_SUCCESS',
    CARDS_PATCH_ERROR: 'CARDS_PATCH_ERROR',

    CARDS_DELETE_REQUEST: 'CARDS_DELETE_REQUEST',
    CARDS_DELETE_SUCCESS: 'CARDS_DELETE_SUCCESS',
    CARDS_DELETE_ERROR: 'CARDS_DELETE_ERROR',
}
